name: CI-code
run-name: ${{ github.actor }} is verify code
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24', '1.25', '1.26' ]

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: subdir/go.sum
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: install go dependencies
        run: |
            go get .

  # validate-code:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: check out repository code
  #       uses: actions/checkout@v6
